# Generated by Django 5.2.18 on 2026-10-10 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0004_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('validado', 'Validado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='generado', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vence_en', models.DateTimeField()),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens_como_tecnico', to=settings.AUTH_USER_MODEL)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='solicitudes.trabajo')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'generado')), fields=('trabajo',), name='uniq_token_generado_por_trabajo'), models.UniqueConstraint(condition=models.Q(('estado', 'generado')), fields=('codigo',), name='uniq_codigo_generado')],
            },
        ),
    ]
