# Generated by Django 5.2.18 on 2026-10-08 21:15

import django.db.models.deletion
import tokens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0004_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=tokens.models.generar_codigo_6_digitos, max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('es_valido', models.BooleanField(default=True)),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_validacion', to='solicitudes.trabajo')),
            ],
            options={
                'verbose_name': 'Token de Trabajo',
                'verbose_name_plural': 'Tokens de Trabajo',
                'db_table': 'tokens_trabajo',
            },
        ),
    ]
