# Generated by Django 5.2.17 on 2026-10-05 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0003_cargar_especialidades_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_preferida', models.DateField(blank=True, null=True)),
                ('es_urgente', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('publicada', 'Publicada'), ('asignada', 'Asignada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='publicada', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='tecnicos.especialidad')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='tecnicos.zona')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'especialidad', 'zona'], name='solicitudes_estado_e6f325_idx')],
            },
        ),
    ]
