# Generated by Django 5.2.17 on 2026-10-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_propuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuesta',
            old_name='precio_estimado',
            new_name='precio',
        ),
    ]
