# Generated by Django 5.2.18 on 2026-10-06 16:44

import django.core.validators
import django.db.models.deletion
import reputacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0004_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=reputacion.models.ruta_foto)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='solicitudes.trabajo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='solicitudes.trabajo')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario'], name='reputacion__destina_5f8774_idx')],
                'constraints': [models.UniqueConstraint(fields=('trabajo', 'autor'), name='uniq_calificacion_trabajo_autor')],
            },
        ),
    ]
