# Generated by Django 5.2.17 on 2026-09-19 18:08

import django.core.validators
import tecnicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltecnico',
            name='dni_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='documento_dni',
            field=models.FileField(blank=True, upload_to='documentos_tecnicos/dni/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), tecnicos.models.validar_tamano_documento]),
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='documento_matricula',
            field=models.FileField(blank=True, upload_to='documentos_tecnicos/matricula/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), tecnicos.models.validar_tamano_documento]),
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='matricula_numero',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
