# Generated by Django 5.2.17 on 2026-09-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('TECNICO', 'Tecnico'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', max_length=20),
        ),
    ]
